### ISSUE TITLE
Remove `tmhOAuth` and replace with PHP League Oauth Client

### ISSUE THREAD

**Issue by atymic** [atymic/twitter#265]
See https://github.com/thephpleague/oauth1-client

**Comment by reliq** [comment]
I think we no longer need this @atymic

**Comment by atymic** [comment]
The current version support the entire oauth signin flow, so I think we still need this, unless the guzzle plugin supports that?

**Comment by reliq** [comment]
I'm not sure I understand this. I think the whole oauth signing process is covered

**Comment by atymic** [comment]
I don't mean the singing flow, I mean the oauth flow to get the token.
Check the section in the readme under "Sign in with twitter"

**Comment by sykezz** [comment]
@atymic The [DM methods on `tmhOAuth` seems to be broken](https://github.com/atymic/twitter/issues/282) right now, and since you're planning to replace `tmhOAuth`, how about [`twitteroauth`](https://github.com/abraham/twitteroauth)? It looks easier than using Guzzle or PHP League OAuth clients (which we may have to use both v1 and v2 versions).

**Comment by atymic** [comment]
I've looked into twitter oauth but would prefer to have minimal dependencies. The guzzle consumers are pretty lightweight, but we'd still need an oauth 1 client.

I'll have another look when I have a chance :)
