### ISSUE TITLE
Why did you abandon laravel-twitter in packagist?

### ISSUE THREAD

**Issue by TheNewSound** [atymic/twitter#277]
Why did you abandon laravel-twitter in packagist?

**Comment by atymic** [comment]
`atymic/laravel-twitter` was my fork of this package, which I created because this package wasn't being maintained. I managed to get in contact with thujohn and he's made the maintainer of the main package.

I merged the changes from my fork back into this package, so my fork is no longer needed and this will be maintained going forward :)

You can just switch your composer.json back to: `thujohn/twitter`

Let me know if you have any other questions
