### ISSUE TITLE
psr/container 2.0 dependency not compatible

### ISSUE THREAD

**Issue by pandooux** [atymic/twitter#389]
On a fresh install of laravel 9, composer install symfony/service-contracts:3.0 which require psr/container:2.0 and this last one is not compatible with php-di/php-di requirement for this package :

"Problem 1
    - atymic/twitter 3.1.15 requires php-di/php-di ^6.2 -> satisfiable by php-di/php-di[6.2.0, ..., 6.3.5].
    - atymic/twitter[3.1.0, ..., 3.1.14] require illuminate/support 6 - 8 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.    - php-di/php-di[6.2.0, ..., 6.3.5] require psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires atymic/twitter ^3.1 -> satisfiable by atymic/twitter[3.1.0, ..., 3.1.15].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require atymic/twitter:*" to figure out if any version is installable, or "composer require atymic/twitter:^2.1" if you know which you need.       

Installation failed, reverting ./composer.json and ./composer.lock to their original content."

Best way I found is to downgrade symfony/service-contract to 2.5 version and then install this package.

Btw, your automated tests are validated because it uses psr/container:1.1.2

**Comment by itrack** [comment]
+1

**Comment by mwakalingajohn** [comment]
I downloaded the packages php-di/php-di and atymic/twitter locally then manually update the psr/container in php-di/php-di to version ^2.0.1. So far nothing is breaking in php-di/php-di package. By updating the version everything worked, there was no more collision with the version in laravel/framework.

**Comment by skull77777** [comment]
> I downloaded the packages php-di/php-di and atymic/twitter locally then manually update the psr/container in php-di/php-di to version ^2.0.1. So far nothing is breaking in php-di/php-di package. By updating the version everything worked, there was no more collision with the version in laravel/framework.

Can you give me step by step instructions for this?

**Comment by mwakalingajohn** [comment]
Here on email? Sent from Mail for Windows From: skull77777Sent: Monday, April 4, 2022 11:35To: atymic/twitterCc: John Mwakalinga; CommentSubject: Re: [atymic/twitter] psr/container 2.0 dependency not compatible (Issue #389) I downloaded the packages php-di/php-di and atymic/twitter locally then manually update the psr/container in php-di/php-di to version ^2.0.1. So far nothing is breaking in php-di/php-di package. By updating the version everything worked, there was no more collision with the version in laravel/framework.Can you give me step by step instructions for this?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by stef686** [comment]
+1

**Comment by bralat** [comment]
Is there a pull request for this yet?

**Comment by atymic** [comment]
@reliq are you able to take a look at this? Otherwise I'll take a look when I'm back.

**Comment by atymic** [comment]
Closed by #411
